repos:
- repo: local
  hooks:
    - id: shellcheck
      name: Test bash source with shellcheck
      entry: koalaman/shellcheck:latest
      language: docker_image
      files: >
        (?x)^(
        install |
        shell/bash/functions |
        shell/bash/profile |
        shell/bash/readline
        )$
      verbose: true
