"show line numbers in hybrid mode (-> relative line numbers, except the current line shows the absolute number)
"tecnically this is not needed with the augroup numbertoggle (see below), it's just there because i dont want that numbertoggle thing to be a dependency for hybrid linenumbers
set number relativenumber

"automatically switch between line number modes. hybrid in normal and command mode, absolute in insert mode and wenn the buffer loses focus
augroup numbertoggle
autocmd!
autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu | set rnu   | endif
autocmd BufLeave,FocusLost,InsertEnter,WinLeave * if &nu | set nornu | endif
augroup END
