#!/usr/bin/env bash
alias e="emacs -nw"
alias ve='env EMACS_USER_DIRECTORY=${XDG_CONFIG_HOME}/emacs/vanilla/.emacs.d emacs -nw'
# -u None don't load vimrc, -N no vi compatible
alias v="vim -u NONE -N"

alias jsonpp="python -c 'import sys, json; print(json.dumps(json.load(sys.stdin), indent=2))'"

# Print each PATH entry on a separate line
# https://askubuntu.com/questions/600018/how-to-display-the-paths-in-path-separately
alias path='echo -e ${PATH//:/\\n}'
alias myip="curl http://checkip.amazonaws.com"

alias ls='ls -F -h --color=always -v --author --time-style=long-iso'
alias ll='ls -l'
alias l='ls -l -a'

alias grep='grep --color=auto'


# docker commands help
alias docker-rm-untagged-images='docker rmi $(docker images -q -f dangling=true)'
alias docker-rm-all-containers='docker rm $(docker ps -aq)'
alias docker-rm-all-exited-containers='docker rm $(docker ps -q -f status=exited)'

# borrow from https://superuser.com/a/511369
alias ssh='compile-ssh-config && ssh'
