#!/usr/bin/env bash
alias e="emacs -nw"
alias jsonpp="python -c 'import sys, json; print(json.dumps(json.load(sys.stdin), indent=2))'"

# Print each PATH entry on a separate line
# https://askubuntu.com/questions/600018/how-to-display-the-paths-in-path-separately
alias path='echo -e ${PATH//:/\\n}'
alias myip="curl http://checkip.amazonaws.com"
alias ve='env EMACS_USER_DIRECTORY=${XDG_CONFIG_HOME}/emacs/vanilla/.emacs.d emacs -nw'
