# shellcheck shell=bash
# shellcheck source=/dev/null
BASH_SOURCE_FILES=(
    opts
    colors
    prompt
    prompt_command
    envs
    aliases
    functions
    completions
    keys
    plugins
    readline
)

for f in "${BASH_SOURCE_FILES[@]}"; do
    if [ -d ~/.bash/"$f" ]; then
        for file in ~/.bash/"$f"/*; do
            source "$file"
        done
    elif [ -e ~/.bash/"$f" ]; then
        source ~/.bash/"$f"
    fi
done

# Local Variables:
# mode: shell-script
# End:
