#!/usr/bin/env bash

_pipsrc()
{
    local cur="${COMP_WORDS[COMP_CWORD]}"
    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "aliyun douban edu" -- "${cur}") )
    else
        COMPREPLY=()
    fi
}
complete -o "nospace" -F _pipsrc pipsrc


# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;

# bash completions
if [[ -n "$BASH_VERSION" ]]; then
    if [ -r /etc/bash_completion ]; then
        # shellcheck disable=SC1091
        source /etc/bash_completion
    fi

    if [ -r /etc/profile.d/bash_completion.sh ]; then
        # shellcheck disable=SC1091
        source /etc/profile.d/bash_completion.sh
    fi

    # https://docs.brew.sh/Shell-Completion
    if [ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]; then
        source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
    else
        for completion in "${HOMEBREW_PREFIX}"/etc/bash_completion.d/*; do
            [ -r "$completion" ] && source "$completion"
        done
    fi
fi
