#!/usr/bin/env bash
_pipsrc()
{
    COMPREPLY=( $(compgen -W "aliyun douban edu") )
}
complete -F _pipsrc pipsrc


# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;
