#!/usr/bin/env bash

export HISTCONTROL="ignoredups:ignorespace"

if command -v emacs >/dev/null 2>&1; then
    EDITOR="$(command -v emacs) -nw -Q"
elif command -v nvim >/dev/null 2>&1; then
    EDITOR="$(command -v nvim)"
elif command -v vim >/dev/null 2>&1; then
    EDITOR="$(command -v vim)"
elif command -v nano >/dev/null 2>&1; then
    EDITOR="$(command -v nano)"
else
    echo "No reasonable text editor is installed on this system! EDITOR will not be explicitly set!"
fi
export EDITOR

# http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:=${HOME}/.config}
export XDG_CACHE_HOME=${XDG_CONFIG_HOME:=${HOME}/.cache}
export XDG_DATA_HOME=${XDG_CONFIG_HOME:=${HOME}/.local/share}

# Set path for inputrc configuration
export INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"
