#!/usr/bin/env bash

export USERPROFILE=$HOME

export HISTCONTROL="ignorespace:erasedups"
export HISTIGNORE="ls:ps:history"
export HISTSIZE=100000
export HISTFILESIZE=10000


if [[ -n "$BASH_VERSION" ]]; then
    set -o emacs
fi

# http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:=${HOME%%/}${HOME:+/}.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:=${HOME%%/}${HOME:+/}.cache}
export XDG_DATA_HOME=${XDG_DATA_HOME:=${HOME%%/}${HOME:+/}.local/share}

# Set path for inputrc configuration
export INPUTRC="${XDG_CONFIG_HOME%%/}${XDG_CONFIG_HOME:+/}readline/inputrc"
#---------------|------remove /------|-if not empty add /|----------------|

export PSQLRC="${PSQLRC:-$XDG_CONFIG_HOME/pg/psqlrc}"
export ENVS_LOCAL="${HOME}/.bash/envs.local"
export SSH_CONFIG_COMMON="${XDG_CONFIG_HOME}/ssh/config.common"
export SSH_CONFIG_LOCAL="$HOME/.ssh/config.local"

if [[ "$OSTYPE" == "msys" ]]; then
    HOSTS="C:\Windows\System32\drivers\etc\hosts"
else
    HOSTS="/etc/hosts"
fi
export HOSTS

if command -v emacs >/dev/null 2>&1; then
    EDITOR="env EMACS_USER_DIRECTORY=${XDG_CONFIG_HOME}/emacs/vanilla/.emacs.d $(command -v emacs) -nw"
elif command -v nvim >/dev/null 2>&1; then
    EDITOR="$(command -v nvim)"
elif command -v vim >/dev/null 2>&1; then
    EDITOR="$(command -v vim)"
elif command -v nano >/dev/null 2>&1; then
    EDITOR="$(command -v nano)"
else
    echo "No reasonable text editor is installed on this system! EDITOR will not be explicitly set!"
fi
export EDITOR

# PYTHONUSERBASE Defines the user base directory, which is used to compute the path of the user site-packages directory and Distutils installation paths for python setup.py install --user.
export PYTHONUSERBASE=${HOME}/.local
export PATH=${PATH}:${PYTHONUSERBASE}/bin
