#!/usr/bin/env bash
# extended cd funtionality
function cd {
    local CWD GIT_ROOT PARENT_GIT_ROOT
    if [ -z "$1" ] && command -v git >/dev/null 2>&1; then
        CWD="$(pwd)"
        if [ "$OSTYPE" = "msys" ]; then
            CWD="$(pwd -W)"
        fi
        GIT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
        if [ -e "${GIT_ROOT}" ]; then
            if [ "${GIT_ROOT}" != "${CWD}" ]; then
                builtin cd "${GIT_ROOT}" && return # toplevel of git repository
            fi
            PARENT_GIT_ROOT="$(builtin cd .. || exit; git rev-parse --show-toplevel 2>/dev/null)"
            if [ -e "${PARENT_GIT_ROOT}" ]; then
                builtin cd "${PARENT_GIT_ROOT}" && return # toplevel of parent git repository
            fi
        fi
    elif [ -f "$1" ]; then # is it a file?
        builtin cd "$(dirname "$1")" && return # cd into enclosing directory
    fi
    builtin cd "$@" && return # normal cd behaviour
}

function server {
    # port 8000 if no port is given. if the 'o' flag is passed, also
    # open the server in a browser.
    local COMMAND=$1;
    if [ "$COMMAND" = "-o" ]; then
        local PORT=${2:-8000}
        open "http://localhost:${PORT}/"
    else
        PORT=${1:-8000}
    fi

    local PY=python
    if command -v ipython >/dev/null 2>&1; then
        PY=ipython
    fi

    ${PY} -c "
import os
try:
    import http.server as httpserver  # py3
    import socketserver
except ImportError:
    import SimpleHTTPServer as httpserver
    import SocketServer as socketserver

Handler = httpserver.SimpleHTTPRequestHandler
m = Handler.extensions_map
m[''] = 'text/plain'
for k in m.keys():
    m[k] = m[k] + '; charset=UTF-8'
httpd = socketserver.TCPServer(('', int('${PORT}')), Handler)
pid = os.getpid()
print('Serving HTTP[pid: {}] on 0.0.0.0 port ${PORT} ...'.format(pid))
try:
    httpd.serve_forever()
except KeyboardInterrupt:
    print('\nInterrupt received, stopping...')
finally:
    httpd.socket.close()
"
}

function pipsrc {
    case "$1" in
        aliyun)
            export PIP_TRUSTED_HOST=mirrors.aliyun.com
            export PIP_INDEX_URL=http://mirrors.aliyun.com/pypi/simple/
            echo "using $1 pip source!!";;
        douban)
            export PIP_TRUSTED_HOST=pypi.doubanio.com
            export PIP_INDEX_URL=https://pypi.doubanio.com/simple/
            echo "using $1 pip source!!";;
        edu)
            export PIP_TRUSTED_HOST=pypi.tuna.tsinghua.edu.cn
            export PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple/
            echo "using $1 pip source!!";;
        *)
            echo "unset pip source!!"
            unset PIP_TRUSTED_HOST
            unset PIP_INDEX_URL
            unset PIPENV_PYPI_MIRROR
    esac

    if [[ -n "$PIP_INDEX_URL"  ]]; then
        export PIPENV_PYPI_MIRROR=$PIP_INDEX_URL
    fi
}

function hex {
    local input
    input="$1"
    if [[ -f "$input" ]]; then
        echo "Hex value of file: $input"
        od -A n -t x1 "$input"
    else
        echo "Hex value of String: $input"
        echo -n "$input" | od -A n -t x1
    fi
}

function pip {
    # https://stackoverflow.com/questions/25399079/how-to-overwrite-a-bash-command
    command pip --version
    command pip "$@"
}

function extract {
    if [ -f "$1" ] ; then
        case $1 in
            *.tar.bz2)  tar xjf "$1"      ;;
            *.tar.gz)   tar xzf "$1"      ;;
            *.bz2)      bunzip2 "$1"      ;;
            *.rar)      rar x "$1"        ;;
            *.gz)       gunzip "$1"       ;;
            *.tar)      tar xf "$1"       ;;
            *.tbz2)     tar xjf "$1"      ;;
            *.tgz)      tar xzf "$1"      ;;
            *.zip)      unzip "$1"        ;;
            *.Z)        uncompress "$1"   ;;
            *)          echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        printf "%s" "'$1' is not a valid file"
    fi
}
