#!/usr/bin/env bash
# alternative set BASHOPTS environment variable
[ -z "$BASH_VERSION" ] && return
if [ "${BASH_VERSINFO[0]}" -gt 4 ]; then
    shopt -s autocd         # cd command if it is a directory
fi
shopt -s cdspell        # try to correct typos in path
shopt -s dotglob        # include dotfiles in path expansion
shopt -s hostcomplete   # try to autocomplete hostnames
shopt -s nocaseglob     # ignore case on glob
shopt -u nullglob       # filename patterns which match no files to expand to a null string eg. * -> empty
shopt -s cmdhist        # store multi-line commands in one history entry
shopt -s histappend     # to append commands to the history file, rather than overwrite it
