- name: Install Django admin completion
  hosts: all
  tasks:
    - name: Get bash-completion for django admin
      get_url:
        url: https://raw.githubusercontent.com/django/django/master/extras/django_bash_completion
        dest: /etc/bash_completion.d/django_bash_completion
