- name: Install docker compose completion
  hosts: all
  tasks:
    - name: Save docker-compose version for following get_url
      shell: docker-compose version --short
      register: docker_compose_version

    - name: Get bash-completion for docker-compose
      get_url:
        url: https://raw.githubusercontent.com/docker/compose/{{ docker_compose_version.stdout }}/contrib/completion/bash/docker-compose
        dest: /etc/bash_completion.d/docker-compose
